version: '2'
services:
    ws-proxy-image :
        image : "node:8.12.0-alpine"
        container_name: ws-proxy-investc
        volumes:
            - .:/var/www
        working_dir: /var/www
        command: sleep 100000000
        ports:
            - "${HOST_PORT}:${HOST_PORT}"
    dev-proxy-image :
        image : "node:8.12.0-alpine"
        container_name: dev-proxy-investc
        volumes:
            - .:/var/www
        working_dir: /var/www
        command: sleep 100000000
    test-proxy-image :
        image : "node:8.12.0-alpine"
        container_name: test-proxy-investc
        volumes:
            - .:/var/www
        working_dir: /var/www
        command: sleep 100000000
        links:
            - ws-proxy-image:ws-proxy-image
    doc-proxy:
        image: schickling/swagger-ui
        ports:
            - "${DOC_PORT}:80"
        environment:
            API_URL: http://0.0.0.0:${HOST_PORT}/doc/api_v1.yaml
            # for v2, use http://0.0.0.0:${HOST_PORT}/doc/api_v2.yaml
